import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";

import "react-loadly/styles.css";
import Navbar from "./_components/navbar/Navbar";
import Cursor from "./_components/Cursor/Cursor";
import Footer from "./_components/footer/Footer";
import ThemeProvider from "./_components/ThemeProvider";
import ParticleBackground from "./_components/Particles/ParticleBackground";
import SocialContact from "./_components/SocialContact/SocialContact";



const suseFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
  ],
});
const robotoFont = Roboto({
  variable: "--font--roboto",
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
  ],
});


export const metadata = {
  description: "Generated by create next app",
  icons: {
    icon:"/icon/profile.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  suppressHydrationWarning>
        <head>
          <title>Mohamed Abdelwahab</title>
        </head>
      <body
        className={`${suseFont.variable} ${robotoFont.variable} relative  antialiased`}>
     
       
           <ThemeProvider
              >
            <ParticleBackground/>
          <Navbar />
          <Cursor /> 
          <SocialContact/>
          <main className="dark:bg-[#0F1726] overflow-hidden  bg-white/85">{children}</main>
          <Footer/>
        </ThemeProvider>
  
       
    
            
        

      </body>
    </html>
  );
}
