import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import "react-loadly/styles.css";
import ThemeProvider from "./_components/ThemeProvider";
import Navbar from "./_components/navbar/Navbar";
import Cursor from "./_components/Cursor/Cursor";
import SocialContact from "./_components/SocialContact/SocialContact";
import Footer from "./_components/footer/Footer";


// 🧠 Fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

// 📝 Metadata (Server-side only)
export const metadata = {
  title: "Mohamed Abdelwahab",
  description: "Generated by create next app",
  icons: {
    icon: "/icon/profile.png",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable} ${roboto.variable} relative antialiased`}>
        <ThemeProvider>
          
          <Navbar />
          <Cursor />
          <SocialContact />
          <main className="dark:bg-[#0F1726]  overflow-hidden">{children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
