import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import "react-loadly/styles.css";
const Navbar=dynamic(()=>import("./_components/navbar/Navbar"));
  const Cursor=dynamic(() =>import  ( "./_components/Cursor/Cursor"));
const Footer=dynamic(()=>import   ( "./_components/footer/Footer"));
const ThemeProvider=dynamic(()=>import  ( "./_components/ThemeProvider"));
const ParticleBackground=dynamic(()=>import  ( "./_components/Particles/ParticleBackground"));
const SocialContact=dynamic(()=>import  ( "./_components/SocialContact/SocialContact"));



const suseFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
  ],
});
const robotoFont = Roboto({
  variable: "--font--roboto",
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
  ],
});


export const metadata = {
  description: "Generated by create next app",
  icons: {
    icon:"/icon/profile.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  suppressHydrationWarning>
        <head>
          <title>Mohamed Abdelwahab</title>
        </head>
      <body
        className={`${suseFont.variable} ${robotoFont.variable} relative  antialiased`}>
     
       
           <ThemeProvider
              >
            <ParticleBackground/>
          <Navbar />
          <Cursor /> 
          <SocialContact/>
          <main className="dark:bg-[#0F1726] overflow-hidden  bg-white/85">{children}</main>
          <Footer/>
        </ThemeProvider>
  
       
    
            
        

      </body>
    </html>
  );
}
/*dynamic import 
دي معناها ان لما اليوزر يوصل للمكون ده هيحصلو تصدير غير كده هو لسه مش موجود
*/
